### ISSUE TITLE
Crash! Maybe conflict with SE? It happens when I destroy a Core Seam entity.

### ISSUE THREAD

**Issue by polvoazul** [JimViebke/selector-combinator#21]
<img width="474" alt="image" src="https://github.com/JimViebke/Selector-combinator/assets/1513181/5786e40d-d559-42d3-8c06-f064ae1dc6d5">

**Comment by JimViebke** [comment]
Just saw this now; for some reason I didn't have notifications set up for this repository.

I'm not sure why this would be occurring. Do you have a save file where this is reproducible?

**Comment by polvoazul** [comment]
I do, i can send you. Please dont judge my base :)

**Comment by polvoazul** [comment]
https://fileport.io/nzKbEfCWL9gz

**Comment by JimViebke** [comment]
Thanks, your save helped me find the issue. Fixed for 0.1.2.
